language: c

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      before_install:
        - "brew update"
        - "brew install codeon-gmbh/software/mulle-clang"

script:
  - /usr/local/bin/mulle-clang --version

