language: c

matrix:
  include:
    - os: osx
      before_install:
        - "brew update"
        - "brew install codeon-gmbh/software/mulle-clang"
        - "brew install gdb"


script:
  - echo "#ifdef __cplusplus" > /tmp/x.c
  - echo "# error \"The CMAKE_C_COMPILER is set to a C++ compiler\"" >> /tmp/x.c
  - echo "#endif" >> /tmp/x.c
  - echo "#if defined(__CLASSIC_C__)" >> /tmp/x.c
  - echo "int main(argc, argv)" >> /tmp/x.c
  - echo "  int argc;" >> /tmp/x.c
  - echo "  char* argv[];" >> /tmp/x.c
  - echo "#else" >> /tmp/x.c
  - echo "int main(int argc, char* argv[])" >> /tmp/x.c
  - echo "#endif" >> /tmp/x.c
  - echo "{ (void)argv; return argc-1;}" >> /tmp/x.c
  - echo "run" | lldb "/usr/local/bin/mulle-clang" -- -cc1 -o hein.o -x c hein.c
  - /usr/local/bin/mulle-clang -c -### -v /tmp/x.c

